server:
  port: 8088
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/foodie
    username: root
    password: mysql

mybatis:
  type-aliases-package: me.zanyrain.foodie.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl